SELECT D.NOME 
FROM DENTISTA D 
WHERE D.CPF IN (SELECT C.CPF_DENTISTA 
FROM CRO C 
WHERE C.CPF_DENTISTA = D.CPF  
AND C.REGISTRO IN (SELECT P.REGISTRO 
FROM CONTROLE_PRESCRICAO P 
GROUP BY P.REGISTRO 
HAVING COUNT(*) > 1 
));

SELECT D.NOME, D.CPF, C.NOME 
FROM DENTISTA D, ATENDIMENTO_DENTISTA A, CONSULTORIO C 
WHERE (D.CPF = A.CPF) 
AND (A.CEP=C.CEP);

SELECT F.NOME, F.CPF, C.NOME 
FROM FUNCIONARIO F, SERVICO S, CONSULTORIO C 
WHERE (F.CPF = S.CPF) 
AND (S.CEP=C.CEP);

SELECT D.NOME AS DENTISTA, F.NOME AS FUNCIONÁRIO, CONCAT(CONCAT(C.ENDERECO, ', '), C.NOME) AS CONSULTÓRIO  
FROM CONSULTORIO C INNER JOIN ATENDIMENTO_DENTISTA A ON (C.CEP = A.CEP) INNER JOIN DENTISTA D ON (D.CPF = A.CPF), FUNCIONARIO F, SERVICO S 
WHERE (S.CEP = A.CEP) AND (S.CPF = F.CPF);

SELECT D.NOME, D.ESPECIALIZACAO1, D.ESPECIALIZACAO2 
FROM DENTISTA D 
WHERE D.ESPECIALIZACAO1 IS NOT NULL AND D.ESPECIALIZACAO2 IS NOT NULL;

SELECT D.NOME, D.ESPECIALIZACAO1, D.ESPECIALIZACAO2 
FROM DENTISTA D 
ORDER BY ESPECIALIZACAO1, D.ESPECIALIZACAO2;

SELECT D.NOME, C.ENDERECO, C.CIDADE 
FROM ATENDIMENTO_DENTISTA A INNER JOIN DENTISTA D ON (D.CPF=A.CPF) INNER JOIN CONSULTORIO C ON (C.CEP=A.CEP) 
WHERE A.EXPEDIENTE LIKE '08:00%';

SELECT P.END_CIDADE, COUNT(*) AS MORADORES 
FROM PACIENTE P 
WHERE P.END_CIDADE IS NOT NULL  
GROUP BY P.END_CIDADE 
HAVING COUNT(*) BETWEEN 1 AND 3;

SELECT END_CIDADE AS CIDADE, COUNT(*) AS NUMERO_DE_PESSOAS 
FROM ( 
SELECT P.END_CIDADE,P.CPF  
FROM PACIENTE p 
UNION ALL 
SELECT D.END_CIDADE, D.CPF 
FROM DENTISTA D 
UNION ALL 
SELECT F.END_CIDADE, F.CPF 
FROM FUNCIONARIO F 
)  
WHERE END_CIDADE IS NOT NULL 
GROUP BY END_CIDADE 
HAVING COUNT(*) BETWEEN 1 AND 3;

SELECT P.END_CIDADE--, COUNT(*) AS NUMERO_DE_PACIENTES, AVG(IDADE) AS MEDIA_IDADE 
FROM (SELECT P.END_CIDADE, P.IDADE 
FROM PACIENTE P 
WHERE P.IDADE > 20 AND P.END_CIDADE IS NOT NULL) P 
GROUP BY END_CIDADE 
HAVING COUNT(*) >= 2 AND AVG(P.IDADE) > 20;

SELECT P.END_CIDADE, MAX(P.IDADE) AS MAIS_VELHO 
FROM PACIENTE P 
WHERE P.END_CIDADE IS NOT NULL 
GROUP BY P.END_CIDADE;

SELECT P.NOME, P.END_CIDADE, P.IDADE AS MAIS_VELHO 
FROM PACIENTE P 
WHERE (P.END_CIDADE, P.IDADE) IN (SELECT P.END_CIDADE, MAX(IDADE) 
FROM PACIENTE P 
WHERE P.END_CIDADE IS NOT NULL 
GROUP BY P.END_CIDADE 
);

SELECT S.CEP, S.ENDERECO, COUNT(*) AS QTD_SALAS  
FROM SALA S 
GROUP BY S.CEP, S.ENDERECO;

SELECT C.ENDERECO 
FROM CONSULTORIO C 
WHERE EXISTS (SELECT * 
FROM ATENDIMENTO_DENTISTA);

SELECT C.ENDERECO 
FROM CONSULTORIO C 
WHERE NOT EXISTS (SELECT * 
FROM SERVICO);

SELECT D.END_CIDADE AS CIDADE, AVG(D.IDADE) AS IDADE_MÉDIA 
FROM DENTISTA D 
WHERE D.END_CIDADE IS NOT NULL 
GROUP BY D.END_CIDADE;

SELECT D.END_CIDADE, AVG(EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM D.NASCIMENTO)) AS MEDIA_IDADE 
FROM DENTISTA D 
WHERE D.END_CIDADE IS NOT NULL 
GROUP BY D.END_CIDADE;

SELECT * 
FROM PACIENTE P 
WHERE P.CONVENIO IS NULL;

SELECT CONCAT(CONCAT(C.ENDERECO, ', '), C.NOME) AS CONSULTÓRIO  
FROM CONSULTORIO C 
WHERE EXISTS (SELECT * 
FROM CONSULTA CO 
WHERE CO.CEP = C.CEP) 
AND EXISTS (SELECT * 
FROM SERVICO S 
WHERE S.CEP = C.CEP) 
AND EXISTS (SELECT * 
FROM PACIENTE P 
WHERE P.CONVENIO IN(SELECT AC.CNPJ 
FROM ACEITA_CONVENIO AC 
WHERE AC.CPF_DENTISTA IN(SELECT A.CPF 
FROM ATENDIMENTO_DENTISTA A 
WHERE A.CEP = C.CEP)));

SELECT M.NOME 
FROM MEDICAMENTO M 
WHERE M.NMR IN (SELECT PR.REMEDIO 
FROM CONTROLE_PRESCRICAO PR);

SELECT CO.MOMENTO_CONSULTA, CO.ENDERECO, CO.VALOR, P.NOME 
FROM CONSULTA CO, PACIENTE P 
WHERE (CO.CPF_PACIENTE = P.CPF) 
AND CO.VALOR > (SELECT TRUNC(AVG(VALOR), 2) FROM CONSULTA);

SELECT DOC.MOMENTO_CONSULTA, DOC.ENDERECO, P.NOME, D.NOME 
FROM DOCUMENTO DOC, PACIENTE P, DENTISTA D 
WHERE DOC.INSTRUCOES LIKE '%Extração%'  
AND (P.CPF=DOC.CPF_PACIENTE) 
AND (D.CPF=DOC.CPF_DENTISTA);

SELECT P.NOME, C.NOME, CO.MOMENTO_CONSULTA, CV.NOME, CO.VALOR, CO.VALOR - (CO.VALOR * CAST(REPLACE(CV.DESCONTO, '%', '') AS FLOAT) / 100) AS VALOR_COM_DESCONTO 
FROM CONSULTA CO INNER JOIN PACIENTE P ON (CO.CPF_PACIENTE=P.CPF) INNER JOIN CONSULTORIO C ON (C.CEP=CO.CEP) INNER JOIN CONVENIO CV ON(P.CONVENIO=CV.CNPJ) 
WHERE CO.VALOR IS NOT NULL AND P.CONVENIO IS NOT NULL;

SELECT COALESCE(TO_CHAR(C.MOMENTO_CONSULTA), 'Nenhuma consulta registrada') AS CONSULTA,  
COALESCE(TO_CHAR(C.VALOR), 'Valor não estimado/consulta não obtida') AS VALOR,  
P.NOME AS NOME_PACIENTE, COALESCE(CV.DESCONTO, 'Sem desconto') AS DESCONTO_CONVÊNIO 
FROM CONSULTA C FULL OUTER JOIN PACIENTE P ON (C.CPF_PACIENTE = P.CPF) FULL OUTER JOIN CONVENIO CV ON P.CONVENIO = CV.CNPJ;

SELECT D.NOME AS DENTISTA, C.NOME AS CONSULTÓRIO 
FROM DENTISTA D LEFT OUTER JOIN ATENDIMENTO_DENTISTA A ON (A.CPF=D.CPF) LEFT OUTER JOIN CONSULTORIO C ON (A.CEP=C.CEP);

