--Cidades que possuem de um a três pacientes registrados(Group by e having)
SELECT P.END_CIDADE, COUNT(*) AS MORADORES
FROM PACIENTE P
WHERE P.END_CIDADE IS NOT NULL 
GROUP BY P.END_CIDADE
HAVING COUNT(*) BETWEEN 1 AND 3;

**Consultório onde não há funcionários(Antijoin)
SELECT C.ENDERECO
FROM CONSULTORIO C
WHERE NOT EXISTS (
    SELECT 1
    FROM SERVICO S
    WHERE S.CEP = C.CEP AND S.ENDERECO = C.ENDERECO
);

--Cpf dos dentistas por nome do consultório que trabalham(INNER J)
SELECT A.CPF, C.NOME
FROM ATENDIMENTO_DENTISTA A, CONSULTORIO C
WHERE (A.CEP=C.CEP);

--**Cidades que possuem de uma a três pessoas registradas(Operação com conjuntos)
SELECT END_CIDADE AS CIDADE, COUNT(*) AS NUMERO_DE_PESSOAS
FROM (
SELECT P.END_CIDADE,P.CPF 
FROM PACIENTE p
UNION ALL
SELECT D.END_CIDADE, D.CPF
FROM DENTISTA D
UNION ALL
SELECT F.END_CIDADE, F.CPF
FROM FUNCIONARIO F
) 
WHERE END_CIDADE IS NOT NULL
GROUP BY END_CIDADE
HAVING COUNT(*) BETWEEN 1 AND 3;

--**Cidades onde há ao menos dois pacientes com mais de 20 anos (Subselect com tabela)
SELECT P.END_CIDADE
FROM (SELECT P.END_CIDADE, P.IDADE
FROM PACIENTE P
WHERE P.IDADE > 20 AND P.END_CIDADE IS NOT NULL) P
GROUP BY END_CIDADE
HAVING COUNT(*) >= 2;

--**Todos os consultório onde dentistas realizaram pelo menos um atendimento, pelo menos um funcionário trabalha e pelo menos um paciente tem convênio aceito por um dentista que trabalha lá.
--(Semijoin)
SELECT CONCAT(CONCAT(C.ENDERECO, ', '), C.NOME) AS CONSULTÓRIO 
FROM CONSULTORIO C
WHERE EXISTS (SELECT *
FROM CONSULTA CO
WHERE CO.CEP = C.CEP)
AND EXISTS (SELECT *
FROM SERVICO S
WHERE S.CEP = C.CEP)
AND EXISTS (SELECT *
FROM PACIENTE P
WHERE P.CONVENIO IN(SELECT AC.CNPJ
FROM ACEITA_CONVENIO AC
WHERE AC.CPF_DENTISTA IN(SELECT A.CPF
FROM ATENDIMENTO_DENTISTA A
WHERE A.CEP = C.CEP)));

--**Consultas com o preço acima da média e nome dos pacientes consultados (Escalar)
SELECT CO.MOMENTO_CONSULTA, CO.ENDERECO, CO.VALOR, P.NOME
FROM CONSULTA CO, PACIENTE P
WHERE (CO.CPF_PACIENTE = P.CPF)
AND CO.VALOR > (SELECT TRUNC(AVG(VALOR), 2) FROM CONSULTA);

--Pacientes sem consultas registradas(JUNÇÃO E)
SELECT P.NOME AS PACIENTE
FROM CONSULTA C RIGHT OUTER JOIN PACIENTE P ON (P.CPF = C.CPF_PACIENTE)
WHERE C.CPF_PACIENTE IS NULL;

--**Dentistas que têm a mesma especialização e moram na mesma cidade que o dentista com CPF '44455566677'(Linha)
SELECT D.NOME
FROM DENTISTA D
WHERE (D.ESPECIALIZACAO1, D.END_CIDADE) = (SELECT D2.ESPECIALIZACAO1, D2.END_CIDADE
FROM DENTISTA D2
WHERE D2.CPF = '44455566677');
