--**Nome dos dentistas que prescreveram mais de um medicamento (Group By e Having)
SELECT D.NOME
FROM DENTISTA D
WHERE D.CPF IN (SELECT C.CPF_DENTISTA
FROM CRO C
WHERE C.CPF_DENTISTA = D.CPF 
AND C.REGISTRO IN (SELECT P.REGISTRO
FROM CONTROLE_PRESCRICAO P
GROUP BY P.REGISTRO
HAVING COUNT(*) > 1
));

--Nome e cpf dos dentistas por nome do consultório que trabalham
SELECT D.NOME, D.CPF, C.NOME
FROM DENTISTA D, ATENDIMENTO_DENTISTA A, CONSULTORIO C
WHERE (D.CPF = A.CPF)
AND (A.CEP=C.CEP);

--Nome e cpf dos funcionário por nome do consultório que trabalham
SELECT F.NOME, F.CPF, C.NOME
FROM FUNCIONARIO F, SERVICO S, CONSULTORIO C
WHERE (F.CPF = S.CPF)
AND (S.CEP=C.CEP);
    
--**CPF e nome de funcionários e dentistas por consultório (Inner Join)
SELECT D.NOME AS DENTISTA, F.NOME AS FUNCIONÁRIO, CONCAT(CONCAT(C.ENDERECO, ', '), C.NOME) AS CONSULTÓRIO 
FROM CONSULTORIO C INNER JOIN ATENDIMENTO_DENTISTA A ON (C.CEP = A.CEP) INNER JOIN DENTISTA D ON (D.CPF = A.CPF), FUNCIONARIO F, SERVICO S
WHERE (S.CEP = A.CEP) AND (S.CPF = F.CPF);

--Nome dos dentistas com mais de uma especialização 
SELECT D.NOME, D.ESPECIALIZACAO1, D.ESPECIALIZACAO2
FROM DENTISTA D
WHERE D.ESPECIALIZACAO1 IS NOT NULL AND D.ESPECIALIZACAO2 IS NOT NULL;

--Dentistas separados por suas especializações
SELECT D.NOME, D.ESPECIALIZACAO1, D.ESPECIALIZACAO2
FROM DENTISTA D
ORDER BY ESPECIALIZACAO1, D.ESPECIALIZACAO2;

--Dentistas que atendem a partir das 08:00 junto ao endereço do consultório
SELECT D.NOME, C.ENDERECO, C.CIDADE
FROM ATENDIMENTO_DENTISTA A INNER JOIN DENTISTA D ON (D.CPF=A.CPF) INNER JOIN CONSULTORIO C ON (C.CEP=A.CEP)
WHERE A.EXPEDIENTE LIKE '08:00%';

--Cidades que possuem de um a três pacientes registrados
SELECT P.END_CIDADE, COUNT(*) AS MORADORES
FROM PACIENTE P
WHERE P.END_CIDADE IS NOT NULL 
GROUP BY P.END_CIDADE
HAVING COUNT(*) BETWEEN 1 AND 3;

--**Cidades que possuem de uma a três pessoas registradas(Operação com conjuntos)
SELECT END_CIDADE AS CIDADE, COUNT(*) AS NUMERO_DE_PESSOAS
FROM (
SELECT P.END_CIDADE,P.CPF 
FROM PACIENTE p
UNION ALL
SELECT D.END_CIDADE, D.CPF
FROM DENTISTA D
UNION ALL
SELECT F.END_CIDADE, F.CPF
FROM FUNCIONARIO F
) 
WHERE END_CIDADE IS NOT NULL
GROUP BY END_CIDADE
HAVING COUNT(*) BETWEEN 1 AND 3;

--**Cidades onde há ao menos dois pacientes com mais de 20 anos e em que a média de idade naquela cidade seja superior a 20 (Subselect com tabela)
SELECT P.END_CIDADE--, COUNT(*) AS NUMERO_DE_PACIENTES, AVG(IDADE) AS MEDIA_IDADE
FROM (SELECT P.END_CIDADE, P.IDADE
FROM PACIENTE P
WHERE P.IDADE > 20 AND P.END_CIDADE IS NOT NULL) P
GROUP BY END_CIDADE
HAVING COUNT(*) >= 2 AND AVG(P.IDADE) > 20;

-- A maior idade de cada cidade
SELECT P.END_CIDADE, MAX(P.IDADE) AS MAIS_VELHO
FROM PACIENTE P
WHERE P.END_CIDADE IS NOT NULL
GROUP BY P.END_CIDADE;

--O mais velho de cada cidade 
SELECT P.NOME, P.END_CIDADE, P.IDADE AS MAIS_VELHO
FROM PACIENTE P
WHERE (P.END_CIDADE, P.IDADE) = ANY (SELECT P.END_CIDADE, MAX(IDADE)
FROM PACIENTE P
WHERE P.END_CIDADE IS NOT NULL
GROUP BY P.END_CIDADE
);

--CEP, endereço e número de salas de cada consultório
SELECT S.CEP, S.ENDERECO, COUNT(*) AS QTD_SALAS 
FROM SALA S
GROUP BY S.CEP, S.ENDERECO;

--Todos os consultórios onde algum dentista atende.
SELECT C.ENDERECO
FROM CONSULTORIO C
WHERE EXISTS (SELECT *
FROM ATENDIMENTO_DENTISTA);

**Consultório onde não há funcionários(Antijoin)
SELECT C.ENDERECO
FROM CONSULTORIO C
WHERE NOT EXISTS (
    SELECT 1
    FROM SERVICO S
    WHERE S.CEP = C.CEP AND S.ENDERECO = C.ENDERECO
);

--Média entre as idades de dentistas da mesma cidade
SELECT D.END_CIDADE AS CIDADE, AVG(D.IDADE) AS IDADE_MÉDIA
FROM DENTISTA D
WHERE D.END_CIDADE IS NOT NULL
GROUP BY D.END_CIDADE;

SELECT D.END_CIDADE, AVG(EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM D.NASCIMENTO)) AS MEDIA_IDADE
FROM DENTISTA D
WHERE D.END_CIDADE IS NOT NULL
GROUP BY D.END_CIDADE;

--Pacientes sem convênio
SELECT *
FROM PACIENTE P
WHERE P.CONVENIO IS NULL;

--**Todos os consultório onde dentistas realizaram pelo menos um atendimento, pelo menos um funcionário trabalha e pelo menos um paciente tem convênio aceito por um dentista que trabalha lá.
--(Semijoin)
SELECT CONCAT(CONCAT(C.ENDERECO, ', '), C.NOME) AS CONSULTÓRIO 
FROM CONSULTORIO C
WHERE EXISTS (SELECT *
FROM CONSULTA CO
WHERE CO.CEP = C.CEP)
AND EXISTS (SELECT *
FROM SERVICO S
WHERE S.CEP = C.CEP)
AND EXISTS (SELECT *
FROM PACIENTE P
WHERE P.CONVENIO IN(SELECT AC.CNPJ
FROM ACEITA_CONVENIO AC
WHERE AC.CPF_DENTISTA IN(SELECT A.CPF
FROM ATENDIMENTO_DENTISTA A
WHERE A.CEP = C.CEP)));

--Todos os medicamentos que estão sendo prescritos
SELECT M.NOME
FROM MEDICAMENTO M
WHERE M.NMR IN (SELECT PR.REMEDIO
FROM CONTROLE_PRESCRICAO PR);

--**Consultas com o preço acima da média e nome dos pacientes consultados (Escalar)
SELECT CO.MOMENTO_CONSULTA, CO.ENDERECO, CO.VALOR, P.NOME
FROM CONSULTA CO, PACIENTE P
WHERE (CO.CPF_PACIENTE = P.CPF)
AND CO.VALOR > (SELECT TRUNC(AVG(VALOR), 2) FROM CONSULTA);

--Consultas associadas a documentos que incluem instruções para extração dentária
SELECT DOC.MOMENTO_CONSULTA, DOC.ENDERECO, P.NOME, D.NOME
FROM DOCUMENTO DOC, PACIENTE P, DENTISTA D
WHERE DOC.INSTRUCOES LIKE '%Extração%' 
AND (P.CPF=DOC.CPF_PACIENTE)
AND (D.CPF=DOC.CPF_DENTISTA);

--Consultas com o valor original e com o valor após o desconto do convênio do paciente atendido
SELECT P.NOME, C.NOME, CO.MOMENTO_CONSULTA, CV.NOME, CO.VALOR, CO.VALOR - (CO.VALOR * CAST(REPLACE(CV.DESCONTO, '%', '') AS FLOAT) / 100) AS VALOR_COM_DESCONTO
FROM CONSULTA CO INNER JOIN PACIENTE P ON (CO.CPF_PACIENTE=P.CPF) INNER JOIN CONSULTORIO C ON (C.CEP=CO.CEP) INNER JOIN CONVENIO CV ON(P.CONVENIO=CV.CNPJ)
WHERE CO.VALOR IS NOT NULL AND P.CONVENIO IS NOT NULL;

--**Projetar todos os pacientes e suas respectivas consultas, preços e descontos pelo convênio, inclusive aqueles que não se consultaram ou não tem convênio ou que não tiveram consulta paga(Junção externa)
SELECT COALESCE(TO_CHAR(C.MOMENTO_CONSULTA), 'Nenhuma consulta registrada') AS CONSULTA, 
COALESCE(TO_CHAR(C.VALOR), 'Valor não estimado/consulta não obtida') AS VALOR, 
P.NOME AS NOME_PACIENTE, COALESCE(CV.DESCONTO, 'Sem desconto') AS DESCONTO_CONVÊNIO
FROM CONSULTA C FULL OUTER JOIN PACIENTE P ON (C.CPF_PACIENTE = P.CPF) FULL OUTER JOIN CONVENIO CV ON P.CONVENIO = CV.CNPJ;

--Dentistas e os respectivos CEP dos consultórios que atendem
SELECT D.NOME AS DENTISTA, C.NOME AS CONSULTÓRIO
FROM DENTISTA D LEFT OUTER JOIN ATENDIMENTO_DENTISTA A ON (A.CPF=D.CPF) LEFT OUTER JOIN CONSULTORIO C ON (A.CEP=C.CEP)

--Pacientes com exceção do mais velho
SELECT P.NOME
FROM PACIENTE P
WHERE P.IDADE < ANY (SELECT IDADE FROM PACIENTE);

--Pacientes que são mais novos que todos os outros de sua cidade
SELECT P1.NOME
FROM PACIENTE P1
WHERE P1.IDADE > ALL (SELECT IDADE FROM PACIENTE P2 WHERE P2.END_CIDADE = P1.END_CIDADE) AND
P1.END_CIDADE IS NOT NULL;

--**Dentistas que têm a mesma especialização e moram na mesma cidade que o dentista com CPF '44455566677'(Linha)
SELECT D.NOME
FROM DENTISTA D
WHERE (D.ESPECIALIZACAO1, D.END_CIDADE) = (SELECT D2.ESPECIALIZACAO1, D2.END_CIDADE
FROM DENTISTA D2
WHERE D2.CPF = '44455566677');

--Dentista que possuem menos consultas que o dentista com maior número de consultas
SELECT D.NOME
FROM DENTISTA D
WHERE (SELECT COUNT(*) 
FROM CONSULTA C 
WHERE C.CPF_DENTISTA = D.CPF) < (SELECT COUNT(*) 
FROM CONSULTA C2 
WHERE C2.CPF_DENTISTA != D.CPF);

--Todas as cidades com pacientes registrados
SELECT DISTINCT P.END_CIDADE
FROM PACIENTE P

--Pacientes e dentistas pelos quais já foram atendidos
SELECT P.NOME AS PACIENTE, D.NOME AS DENTISTA
FROM CONSULTA C, PACIENTE P, DENTISTA D
WHERE (C.CPF_PACIENTE = P.CPF) AND
(C.CPF_DENTISTA = D.CPF);

--Pacientes e seus respectivos pacientes mais novos
SELECT P1.NOME, P2.NOME
FROM PACIENTE P1 INNER JOIN PACIENTE P2 ON (P1.IDADE > P2.IDADE)

--Pacientes sem consultas registradas
SELECT P.NOME AS PACIENTE
FROM CONSULTA C RIGHT OUTER JOIN PACIENTE P ON (P.CPF = C.CPF_PACIENTE)
WHERE C.CPF_PACIENTE IS NULL;
